import java.util.Random;
import java.util.*;
public class Number_game{
    public static void guessing_game(){
        Random rand=new Random();
        int numberToGuess=rand.nextInt(100)+1;
        int numberofTries=0;
        Scanner sc=new Scanner(System.in);
        boolean win=false;
        
        System.out.println("Welcome to Number Game!! In this Game you have to predict the correct number generated by computer in between range 1 to 100");
        System.out.println("The player will get 10 attempts to predict the correct number");
        
        while(win==false){
            System.out.println("Guess the number in between range 1 to 100");
            int guess=sc.nextInt();
            numberofTries++;

            if(guess==numberToGuess){
               win=true;
            }
            else if(guess>numberToGuess){
                   System.out.println("your guess is too high");
            }
            else if(guess<numberToGuess){
                   System.out.println("your guess is too low");
            }
            if(numberofTries==10){
                break;
           }

        }
        if(win==true){
    
            System.out.println("you won the game");
            System.out.println("The correct number is "+numberToGuess);
            System.out.println("you predict the correct number in "+numberofTries+" tries");
            System.out.println("your score is "+(10-numberofTries+1)+" out of 10 as you predict the correct number in "+numberofTries+" tries");
        }
        else if(numberofTries==10){
            System.out.println("you lost the game as your number of tries exhausted");
            System.out.println("The correct number is "+numberToGuess);
            System.out.println("your score is 0 out of 10");
        } 
        System.out.println(); 
    }
    public static void main(String args[]){
        Scanner sc=new Scanner(System.in);
        guessing_game();
        boolean game=true;

        while(game==true){
            System.out.println("do you want to play the game again ?? press 1 for yes and 0 for no");
            int number =sc.nextInt();

            if(number==1){
              guessing_game();
            }
            else{
               game=false;
            }
        } 
        System.out.println("Game Over !!");  

         sc.close();
    }
}